[book]
authors = ["Pedro"]
language = "es"
src = "src_doc"
title = "BabelcomicsR - Manual y Documentación Técnica"

[preprocessor.links]

[output.html]
git-repository-url = "https://github.com/tu-usuario/BabelcomicsR"
edit-url-template = "https://github.com/tu-usuario/BabelcomicsR/edit/main/src_doc/{path}"
